worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # TODO 1: definisikan upstream block bernama "app_backend" berisi
    # 3 server: app1:8000, app2:8000, app3:8000
    #
    # upstream app_backend {
    #     server app1:8000;
    #     server app2:8000;
    #     server app3:8000;
    # }

    server {
        listen 80;

        location / {
            # TODO 2: proxy_pass ke http://app_backend (nama upstream di atas)
            proxy_pass http://__ISI_NAMA_UPSTREAM__;
        }
    }
}
